# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x07kurumai\x1a\x0c\x63ommon.proto\"\xfe\x01\n\x0bSocketEvent\x12\x12\n\x05\x65vent\x18\x01 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\tH\x02\x88\x01\x01\x12*\n\x0btts_message\x18\x03 \x01(\x0b\x32\x13.kurumai.TTSMessageH\x00\x12#\n\x07message\x18\x04 \x01(\x0b\x32\x10.kurumai.MessageH\x00\x12.\n\rstart_message\x18\x05 \x01(\x0b\x32\x15.kurumai.StartMessageH\x00\x12-\n\x0c\x63onversation\x18\x06 \x01(\x0b\x32\x15.kurumai.ConversationH\x00\x42\t\n\x07payloadB\x08\n\x06_eventB\x05\n\x03_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOCKETEVENT']._serialized_start=40
  _globals['_SOCKETEVENT']._serialized_end=294
# @@protoc_insertion_point(module_scope)
